//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomethingWickedServerLegacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bios
    {
        public int BioID { get; set; }
        public string Bio { get; set; }
        public int MemberID { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
