//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomethingWickedServerLegacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Something_WickedEntities : DbContext
    {
        public Something_WickedEntities()
            : base("name=Something_WickedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bios> Bios { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ShowcaseImages> ShowcaseImages { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
        public virtual DbSet<Venues> Venues { get; set; }
        public virtual DbSet<VideoGroups> VideoGroups { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
    }
}
