//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomethingWickedServerLegacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public string Song { get; set; }
        public string Artist { get; set; }
        public int GenreID { get; set; }
        public string VideoGroup { get; set; }
        public string VideoID { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
